services:
  db:
    ports:
      - "5431:5432"
    image: postgres
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./docker_test_db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 5s
      timeout: 60s
      retries: 5
      start_period: 80s

  server:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT = ${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file:
      - .env
    volumes:
      - ./:/usr/local/server
      - exclude:/usr/local/server/node_modules/
    depends_on:
      db:
        condition: service_healthy

volumes:
  exclude: